version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.1"
    steps:
      - checkout
      - run: python3 calc.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.1"
    steps:
      - checkout
      - run: python3 test_calc.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
